# -*- coding: utf-8 -*-
"""DAY 6 TASK.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a1I4mtIBJt8n5XsMhPgI--STL4cuz3d1

**Day 6 – Dictionary, Sets**

**Exercise:**

**1) Write a Python script to merge two Python dictionaries**
"""

#creating two dictionaries
dict1={'Sneha':85,'Arjun':18,'Meenu':57,'Sree':88}
dict2={'Sai':76,'Madhav':56,'Akshay':12,'Nandhu':67}
#merging two dictionaries using update() method
dict1.update(dict2)
print("Merged Dictionaries =",dict1)

#merging two dictionaries using ** operator
dict3={**dict1,**dict2}
print("Merged Dictionaries =",dict3)

"""**2) Write a Python program to remove a key from a dictionary**"""

#remove a key from a dictionary using del 
del dict1['Nandhu']
print("After removing a key=",dict1)

#remove a key from a dictionary using pop()
dict4={'Kavitha':100,'Sanil':101,'Vinod':102,'Ambili':103,'Sudha':104,'Mohan':105}
dict4.pop('Mohan')
print("After removing a key=",dict4)

"""**3) Write a Python program to map two lists into a dictionary**"""

#map two lists into a dictionary
keys = ['Name', 'Age', 'Job']
values = ['Sneha', 19, 'Coder']
myDict = dict(zip(keys, values))
print("Dictionary Items =",myDict)

"""**4) Write a Python program to find the length of a set**



"""

#length of a set
set1=(1265,896,325,925,65,582,327,83,685,832,472)
print("Length of set =",len(set1))

"""**5) Write a Python program to remove the intersection of a 2nd set from the 
1st set**
"""

#intersection of a 2nd set from the 1st set
s1 = {8,4,2,5,6,5,3,1}
s2 = {3,1,7,9,5}
s1.intersection(s2)